services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: doheem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
