// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateGroup = `-- name: ActivateGroup :exec
UPDATE groups
SET is_active = true,
    inactive_since = NULL,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ActivateGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateGroup, id)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, currency)
VALUES ($1, $2)
RETURNING id, name, currency, is_active, inactive_since, created_at, updated_at, deleted_at
`

type CreateGroupParams struct {
	Name     string
	Currency string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Currency)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateGroup = `-- name: DeactivateGroup :exec
UPDATE groups
SET is_active = false,
    inactive_since = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeactivateGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, currency, is_active, inactive_since, created_at, updated_at, deleted_at FROM groups
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGroupsByUserID = `-- name: ListGroupsByUserID :many
SELECT g.id, g.name, g.currency, g.is_active, g.inactive_since, g.created_at, g.updated_at, g.deleted_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1 AND g.deleted_at IS NULL AND gm.is_active = true
ORDER BY g.name
`

func (q *Queries) ListGroupsByUserID(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.IsActive,
			&i.InactiveSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE groups
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteGroup, id)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = COALESCE($2, name),
    currency = COALESCE($3, currency),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, currency, is_active, inactive_since, created_at, updated_at, deleted_at
`

type UpdateGroupParams struct {
	ID       pgtype.UUID
	Name     string
	Currency string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Currency)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
