// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallment = `-- name: CreateInstallment :one
INSERT INTO installments (expense_id, installment_number, amount, due_date)
VALUES ($1, $2, $3, $4)
RETURNING id, expense_id, installment_number, amount, due_date, is_paid, paid_at, created_at
`

type CreateInstallmentParams struct {
	ExpenseID         pgtype.UUID
	InstallmentNumber int16
	Amount            pgtype.Numeric
	DueDate           pgtype.Date
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, createInstallment,
		arg.ExpenseID,
		arg.InstallmentNumber,
		arg.Amount,
		arg.DueDate,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.InstallmentNumber,
		&i.Amount,
		&i.DueDate,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

type CreateInstallmentsParams struct {
	ExpenseID         pgtype.UUID
	InstallmentNumber int16
	Amount            pgtype.Numeric
	DueDate           pgtype.Date
}

const deleteInstallmentsByExpense = `-- name: DeleteInstallmentsByExpense :exec
DELETE FROM installments
WHERE expense_id = $1
`

func (q *Queries) DeleteInstallmentsByExpense(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInstallmentsByExpense, expenseID)
	return err
}

const getInstallmentByID = `-- name: GetInstallmentByID :one
SELECT id, expense_id, installment_number, amount, due_date, is_paid, paid_at, created_at FROM installments
WHERE id = $1
`

func (q *Queries) GetInstallmentByID(ctx context.Context, id pgtype.UUID) (Installment, error) {
	row := q.db.QueryRow(ctx, getInstallmentByID, id)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.InstallmentNumber,
		&i.Amount,
		&i.DueDate,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInstallmentsByExpense = `-- name: ListInstallmentsByExpense :many
SELECT id, expense_id, installment_number, amount, due_date, is_paid, paid_at, created_at FROM installments
WHERE expense_id = $1
ORDER BY installment_number
`

func (q *Queries) ListInstallmentsByExpense(ctx context.Context, expenseID pgtype.UUID) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsByExpense, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.InstallmentNumber,
			&i.Amount,
			&i.DueDate,
			&i.IsPaid,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallmentAsPaid = `-- name: MarkInstallmentAsPaid :exec
UPDATE installments
SET is_paid = true,
    paid_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkInstallmentAsPaid(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markInstallmentAsPaid, id)
	return err
}
