// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (group_id, code, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, code, created_by, expires_at, used_at, revoked_at, created_at
`

type CreateInviteParams struct {
	GroupID   pgtype.UUID
	Code      string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.GroupID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT i.id, i.group_id, i.code, i.created_by, i.expires_at, i.used_at, i.revoked_at, i.created_at, g.name AS group_name
FROM invites i
JOIN groups g ON g.id = i.group_id
WHERE i.code = $1 AND i.used_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > NOW()
`

type GetInviteByCodeRow struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Code      string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	GroupName string
}

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (GetInviteByCodeRow, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i GetInviteByCodeRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.GroupName,
	)
	return i, err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT id, group_id, code, created_by, expires_at, used_at, revoked_at, created_at FROM invites
WHERE id = $1
`

func (q *Queries) GetInviteByID(ctx context.Context, id pgtype.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByID, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitesByGroup = `-- name: ListInvitesByGroup :many
SELECT i.id, i.group_id, i.code, i.created_by, i.expires_at, i.used_at, i.revoked_at, i.created_at, u.name AS created_by_name
FROM invites i
JOIN users u ON u.id = i.created_by
WHERE i.group_id = $1
ORDER BY i.created_at DESC
`

type ListInvitesByGroupRow struct {
	ID            pgtype.UUID
	GroupID       pgtype.UUID
	Code          string
	CreatedBy     pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
	UsedAt        pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	CreatedByName string
}

func (q *Queries) ListInvitesByGroup(ctx context.Context, groupID pgtype.UUID) ([]ListInvitesByGroupRow, error) {
	rows, err := q.db.Query(ctx, listInvitesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitesByGroupRow
	for rows.Next() {
		var i ListInvitesByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Code,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitesByUser = `-- name: ListPendingInvitesByUser :many
SELECT i.id, i.group_id, i.code, i.created_by, i.expires_at, i.used_at, i.revoked_at, i.created_at, g.name AS group_name
FROM invites i
JOIN groups g ON g.id = i.group_id
JOIN group_members gm ON gm.group_id = i.group_id AND gm.user_id = $1
WHERE i.used_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > NOW()
ORDER BY i.created_at DESC
`

type ListPendingInvitesByUserRow struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Code      string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	GroupName string
}

func (q *Queries) ListPendingInvitesByUser(ctx context.Context, userID pgtype.UUID) ([]ListPendingInvitesByUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitesByUserRow
	for rows.Next() {
		var i ListPendingInvitesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Code,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites
SET revoked_at = NOW()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) RevokeInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeInvite, id)
	return err
}

const useInvite = `-- name: UseInvite :exec
UPDATE invites
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) UseInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useInvite, id)
	return err
}
