// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID
	GroupID    pgtype.UUID
	UserID     pgtype.UUID
	EntityType string
	EntityID   pgtype.UUID
	Action     string
	Changes    []byte
	CreatedAt  pgtype.Timestamptz
}

type Expense struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	CreatedBy        pgtype.UUID
	Description      string
	TotalAmount      pgtype.Numeric
	ExpenseDate      pgtype.Date
	DueDate          pgtype.Date
	CategoryID       pgtype.UUID
	SplitType        string
	IsInstallment    bool
	InstallmentCount pgtype.Int2
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ExpenseCategory struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type ExpenseSplit struct {
	ID        pgtype.UUID
	ExpenseID pgtype.UUID
	UserID    pgtype.UUID
	Amount    pgtype.Numeric
	IsPaid    bool
	PaidAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Group struct {
	ID            pgtype.UUID
	Name          string
	Currency      string
	IsActive      bool
	InactiveSince pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type GroupMember struct {
	ID       pgtype.UUID
	GroupID  pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
	LeftAt   pgtype.Timestamptz
	IsActive bool
}

type Installment struct {
	ID                pgtype.UUID
	ExpenseID         pgtype.UUID
	InstallmentNumber int16
	Amount            pgtype.Numeric
	DueDate           pgtype.Date
	IsPaid            bool
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Invite struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Code      string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Notification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	GroupID   pgtype.UUID
	Type      string
	Title     string
	Message   string
	IsRead    bool
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Payment struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	PayerID     pgtype.UUID
	ReceiverID  pgtype.UUID
	Amount      pgtype.Numeric
	PaymentDate pgtype.Date
	Status      string
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ConfirmedAt pgtype.Timestamptz
	CancelledAt pgtype.Timestamptz
}

type PaymentAttachment struct {
	ID         pgtype.UUID
	PaymentID  pgtype.UUID
	FilePath   string
	FileType   string
	FileSize   int32
	UploadedAt pgtype.Timestamptz
}

type SplitTag struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Name      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type SplitTagMember struct {
	ID         pgtype.UUID
	SplitTagID pgtype.UUID
	UserID     pgtype.UUID
}

type Task struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	Title            string
	Description      pgtype.Text
	AssignedTo       pgtype.UUID
	Category         pgtype.Text
	IsRecurring      bool
	RecurringPeriod  pgtype.Text
	RecurringEndedAt pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TaskOccurrence struct {
	ID          pgtype.UUID
	TaskID      pgtype.UUID
	DueDate     pgtype.Date
	Status      string
	CompletedBy pgtype.UUID
	CompletedAt pgtype.Timestamptz
	DiscardedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
