// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_occurrence.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTaskOccurrence = `-- name: CompleteTaskOccurrence :exec
UPDATE task_occurrences
SET status = 'completed',
    completed_by = $2,
    completed_at = NOW()
WHERE id = $1 AND status = 'pending'
`

type CompleteTaskOccurrenceParams struct {
	ID          pgtype.UUID
	CompletedBy pgtype.UUID
}

func (q *Queries) CompleteTaskOccurrence(ctx context.Context, arg CompleteTaskOccurrenceParams) error {
	_, err := q.db.Exec(ctx, completeTaskOccurrence, arg.ID, arg.CompletedBy)
	return err
}

const createTaskOccurrence = `-- name: CreateTaskOccurrence :one
INSERT INTO task_occurrences (task_id, due_date, status)
VALUES ($1, $2, $3)
RETURNING id, task_id, due_date, status, completed_by, completed_at, discarded_at, created_at
`

type CreateTaskOccurrenceParams struct {
	TaskID  pgtype.UUID
	DueDate pgtype.Date
	Status  string
}

func (q *Queries) CreateTaskOccurrence(ctx context.Context, arg CreateTaskOccurrenceParams) (TaskOccurrence, error) {
	row := q.db.QueryRow(ctx, createTaskOccurrence, arg.TaskID, arg.DueDate, arg.Status)
	var i TaskOccurrence
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DueDate,
		&i.Status,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskOccurrencesByTask = `-- name: DeleteTaskOccurrencesByTask :exec
DELETE FROM task_occurrences
WHERE task_id = $1
`

func (q *Queries) DeleteTaskOccurrencesByTask(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskOccurrencesByTask, taskID)
	return err
}

const discardTaskOccurrence = `-- name: DiscardTaskOccurrence :exec
UPDATE task_occurrences
SET status = 'discarded',
    discarded_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DiscardTaskOccurrence(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, discardTaskOccurrence, id)
	return err
}

const getTaskOccurrenceByID = `-- name: GetTaskOccurrenceByID :one
SELECT id, task_id, due_date, status, completed_by, completed_at, discarded_at, created_at FROM task_occurrences
WHERE id = $1
`

func (q *Queries) GetTaskOccurrenceByID(ctx context.Context, id pgtype.UUID) (TaskOccurrence, error) {
	row := q.db.QueryRow(ctx, getTaskOccurrenceByID, id)
	var i TaskOccurrence
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DueDate,
		&i.Status,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.DiscardedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingTaskOccurrencesByUser = `-- name: ListPendingTaskOccurrencesByUser :many
SELECT to2.id, to2.task_id, to2.due_date, to2.status, to2.completed_by, to2.completed_at, to2.discarded_at, to2.created_at, t.title AS task_title, t.group_id
FROM task_occurrences to2
JOIN tasks t ON t.id = to2.task_id
WHERE to2.status = 'pending' AND t.assigned_to = $1
ORDER BY to2.due_date
`

type ListPendingTaskOccurrencesByUserRow struct {
	ID          pgtype.UUID
	TaskID      pgtype.UUID
	DueDate     pgtype.Date
	Status      string
	CompletedBy pgtype.UUID
	CompletedAt pgtype.Timestamptz
	DiscardedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	TaskTitle   string
	GroupID     pgtype.UUID
}

func (q *Queries) ListPendingTaskOccurrencesByUser(ctx context.Context, assignedTo pgtype.UUID) ([]ListPendingTaskOccurrencesByUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingTaskOccurrencesByUser, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTaskOccurrencesByUserRow
	for rows.Next() {
		var i ListPendingTaskOccurrencesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DueDate,
			&i.Status,
			&i.CompletedBy,
			&i.CompletedAt,
			&i.DiscardedAt,
			&i.CreatedAt,
			&i.TaskTitle,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskOccurrencesByDateRange = `-- name: ListTaskOccurrencesByDateRange :many
SELECT to2.id, to2.task_id, to2.due_date, to2.status, to2.completed_by, to2.completed_at, to2.discarded_at, to2.created_at, t.title AS task_title, t.group_id
FROM task_occurrences to2
JOIN tasks t ON t.id = to2.task_id
WHERE t.group_id = $1 AND to2.due_date BETWEEN $2 AND $3
ORDER BY to2.due_date
`

type ListTaskOccurrencesByDateRangeParams struct {
	GroupID   pgtype.UUID
	DueDate   pgtype.Date
	DueDate_2 pgtype.Date
}

type ListTaskOccurrencesByDateRangeRow struct {
	ID          pgtype.UUID
	TaskID      pgtype.UUID
	DueDate     pgtype.Date
	Status      string
	CompletedBy pgtype.UUID
	CompletedAt pgtype.Timestamptz
	DiscardedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	TaskTitle   string
	GroupID     pgtype.UUID
}

func (q *Queries) ListTaskOccurrencesByDateRange(ctx context.Context, arg ListTaskOccurrencesByDateRangeParams) ([]ListTaskOccurrencesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listTaskOccurrencesByDateRange, arg.GroupID, arg.DueDate, arg.DueDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskOccurrencesByDateRangeRow
	for rows.Next() {
		var i ListTaskOccurrencesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DueDate,
			&i.Status,
			&i.CompletedBy,
			&i.CompletedAt,
			&i.DiscardedAt,
			&i.CreatedAt,
			&i.TaskTitle,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskOccurrencesByTask = `-- name: ListTaskOccurrencesByTask :many
SELECT id, task_id, due_date, status, completed_by, completed_at, discarded_at, created_at FROM task_occurrences
WHERE task_id = $1
ORDER BY due_date
`

func (q *Queries) ListTaskOccurrencesByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskOccurrence, error) {
	rows, err := q.db.Query(ctx, listTaskOccurrencesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskOccurrence
	for rows.Next() {
		var i TaskOccurrence
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DueDate,
			&i.Status,
			&i.CompletedBy,
			&i.CompletedAt,
			&i.DiscardedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskOccurrenceAsOverdue = `-- name: MarkTaskOccurrenceAsOverdue :exec
UPDATE task_occurrences
SET status = 'overdue'
WHERE id = $1 AND status = 'pending' AND due_date < CURRENT_DATE
`

func (q *Queries) MarkTaskOccurrenceAsOverdue(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTaskOccurrenceAsOverdue, id)
	return err
}
