// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (group_id, title, description, assigned_to, category, is_recurring, recurring_period, recurring_ended_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, group_id, title, description, assigned_to, category, is_recurring, recurring_period, recurring_ended_at, created_by, created_at, updated_at
`

type CreateTaskParams struct {
	GroupID          pgtype.UUID
	Title            string
	Description      pgtype.Text
	AssignedTo       pgtype.UUID
	Category         pgtype.Text
	IsRecurring      bool
	RecurringPeriod  pgtype.Text
	RecurringEndedAt pgtype.Timestamptz
	CreatedBy        pgtype.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.AssignedTo,
		arg.Category,
		arg.IsRecurring,
		arg.RecurringPeriod,
		arg.RecurringEndedAt,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.AssignedTo,
		&i.Category,
		&i.IsRecurring,
		&i.RecurringPeriod,
		&i.RecurringEndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, group_id, title, description, assigned_to, category, is_recurring, recurring_period, recurring_ended_at, created_by, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.AssignedTo,
		&i.Category,
		&i.IsRecurring,
		&i.RecurringPeriod,
		&i.RecurringEndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT id, group_id, title, description, assigned_to, category, is_recurring, recurring_period, recurring_ended_at, created_by, created_at, updated_at FROM tasks
WHERE assigned_to = $1 AND group_id = $2
ORDER BY created_at DESC
`

type ListTasksByAssigneeParams struct {
	AssignedTo pgtype.UUID
	GroupID    pgtype.UUID
}

func (q *Queries) ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee, arg.AssignedTo, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.AssignedTo,
			&i.Category,
			&i.IsRecurring,
			&i.RecurringPeriod,
			&i.RecurringEndedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByGroup = `-- name: ListTasksByGroup :many
SELECT id, group_id, title, description, assigned_to, category, is_recurring, recurring_period, recurring_ended_at, created_by, created_at, updated_at FROM tasks
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByGroup(ctx context.Context, groupID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.AssignedTo,
			&i.Category,
			&i.IsRecurring,
			&i.RecurringPeriod,
			&i.RecurringEndedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = COALESCE($2, title),
    description = $3,
    assigned_to = $4,
    category = $5,
    is_recurring = COALESCE($6, is_recurring),
    recurring_period = $7,
    recurring_ended_at = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, title, description, assigned_to, category, is_recurring, recurring_period, recurring_ended_at, created_by, created_at, updated_at
`

type UpdateTaskParams struct {
	ID               pgtype.UUID
	Title            string
	Description      pgtype.Text
	AssignedTo       pgtype.UUID
	Category         pgtype.Text
	IsRecurring      bool
	RecurringPeriod  pgtype.Text
	RecurringEndedAt pgtype.Timestamptz
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AssignedTo,
		arg.Category,
		arg.IsRecurring,
		arg.RecurringPeriod,
		arg.RecurringEndedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.AssignedTo,
		&i.Category,
		&i.IsRecurring,
		&i.RecurringPeriod,
		&i.RecurringEndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
