// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (group_id, user_id, entity_type, entity_id, action, changes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, user_id, entity_type, entity_id, action, changes, created_at
`

type CreateAuditLogParams struct {
	GroupID    pgtype.UUID
	UserID     pgtype.UUID
	EntityType string
	EntityID   pgtype.UUID
	Action     string
	Changes    []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.GroupID,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Changes,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, group_id, user_id, entity_type, entity_id, action, changes, created_at FROM audit_logs
WHERE id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, group_id, user_id, entity_type, entity_id, action, changes, created_at FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListAuditLogsByEntityParams struct {
	EntityType string
	EntityID   pgtype.UUID
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByGroup = `-- name: ListAuditLogsByGroup :many
SELECT al.id, al.group_id, al.user_id, al.entity_type, al.entity_id, al.action, al.changes, al.created_at, u.name AS user_name
FROM audit_logs al
LEFT JOIN users u ON u.id = al.user_id
WHERE al.group_id = $1
ORDER BY al.created_at DESC
`

type ListAuditLogsByGroupRow struct {
	ID         pgtype.UUID
	GroupID    pgtype.UUID
	UserID     pgtype.UUID
	EntityType string
	EntityID   pgtype.UUID
	Action     string
	Changes    []byte
	CreatedAt  pgtype.Timestamptz
	UserName   pgtype.Text
}

func (q *Queries) ListAuditLogsByGroup(ctx context.Context, groupID pgtype.UUID) ([]ListAuditLogsByGroupRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsByGroupRow
	for rows.Next() {
		var i ListAuditLogsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
