// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateExpenseSplits implements pgx.CopyFromSource.
type iteratorForCreateExpenseSplits struct {
	rows                 []CreateExpenseSplitsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateExpenseSplits) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateExpenseSplits) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ExpenseID,
		r.rows[0].UserID,
		r.rows[0].Amount,
	}, nil
}

func (r iteratorForCreateExpenseSplits) Err() error {
	return nil
}

func (q *Queries) CreateExpenseSplits(ctx context.Context, arg []CreateExpenseSplitsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"expense_splits"}, []string{"expense_id", "user_id", "amount"}, &iteratorForCreateExpenseSplits{rows: arg})
}
