// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_split.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseSplit = `-- name: CreateExpenseSplit :one
INSERT INTO expense_splits (expense_id, user_id, amount)
VALUES ($1, $2, $3)
RETURNING id, expense_id, user_id, amount, is_paid, paid_at, created_at
`

type CreateExpenseSplitParams struct {
	ExpenseID pgtype.UUID
	UserID    pgtype.UUID
	Amount    pgtype.Numeric
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, createExpenseSplit, arg.ExpenseID, arg.UserID, arg.Amount)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

type CreateExpenseSplitsParams struct {
	ExpenseID pgtype.UUID
	UserID    pgtype.UUID
	Amount    pgtype.Numeric
}

const deleteExpenseSplitsByExpense = `-- name: DeleteExpenseSplitsByExpense :exec
DELETE FROM expense_splits
WHERE expense_id = $1
`

func (q *Queries) DeleteExpenseSplitsByExpense(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseSplitsByExpense, expenseID)
	return err
}

const getExpenseSplitByID = `-- name: GetExpenseSplitByID :one
SELECT id, expense_id, user_id, amount, is_paid, paid_at, created_at FROM expense_splits
WHERE id = $1
`

func (q *Queries) GetExpenseSplitByID(ctx context.Context, id pgtype.UUID) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, getExpenseSplitByID, id)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
		&i.IsPaid,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBalanceInGroup = `-- name: GetUserBalanceInGroup :one
SELECT COALESCE(SUM(es.amount), 0)::NUMERIC(12,2) AS total_owed,
       COALESCE(SUM(CASE WHEN es.is_paid THEN es.amount ELSE 0 END), 0)::NUMERIC(12,2) AS total_paid
FROM expense_splits es
JOIN expenses e ON e.id = es.expense_id
WHERE es.user_id = $1 AND e.group_id = $2
`

type GetUserBalanceInGroupParams struct {
	UserID  pgtype.UUID
	GroupID pgtype.UUID
}

type GetUserBalanceInGroupRow struct {
	TotalOwed pgtype.Numeric
	TotalPaid pgtype.Numeric
}

func (q *Queries) GetUserBalanceInGroup(ctx context.Context, arg GetUserBalanceInGroupParams) (GetUserBalanceInGroupRow, error) {
	row := q.db.QueryRow(ctx, getUserBalanceInGroup, arg.UserID, arg.GroupID)
	var i GetUserBalanceInGroupRow
	err := row.Scan(&i.TotalOwed, &i.TotalPaid)
	return i, err
}

const hasExpensePaidSplits = `-- name: HasExpensePaidSplits :one
SELECT EXISTS(
  SELECT 1 FROM expense_splits
  WHERE expense_id = $1 AND is_paid = true
)
`

func (q *Queries) HasExpensePaidSplits(ctx context.Context, expenseID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasExpensePaidSplits, expenseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listExpenseSplitsByExpense = `-- name: ListExpenseSplitsByExpense :many
SELECT es.id, es.expense_id, es.user_id, es.amount, es.is_paid, es.paid_at, es.created_at, u.name AS user_name, u.email AS user_email
FROM expense_splits es
JOIN users u ON u.id = es.user_id
WHERE es.expense_id = $1
ORDER BY es.amount DESC
`

type ListExpenseSplitsByExpenseRow struct {
	ID        pgtype.UUID
	ExpenseID pgtype.UUID
	UserID    pgtype.UUID
	Amount    pgtype.Numeric
	IsPaid    bool
	PaidAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UserName  string
	UserEmail string
}

func (q *Queries) ListExpenseSplitsByExpense(ctx context.Context, expenseID pgtype.UUID) ([]ListExpenseSplitsByExpenseRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByExpense, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsByExpenseRow
	for rows.Next() {
		var i ListExpenseSplitsByExpenseRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.Amount,
			&i.IsPaid,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseSplitsByExpenseIDs = `-- name: ListExpenseSplitsByExpenseIDs :many
SELECT es.id, es.expense_id, es.user_id, es.amount, es.is_paid, es.paid_at, es.created_at, u.name AS user_name, u.email AS user_email
FROM expense_splits es
JOIN users u ON u.id = es.user_id
WHERE es.expense_id = ANY($1::uuid[])
ORDER BY es.expense_id, es.amount DESC
`

type ListExpenseSplitsByExpenseIDsRow struct {
	ID        pgtype.UUID
	ExpenseID pgtype.UUID
	UserID    pgtype.UUID
	Amount    pgtype.Numeric
	IsPaid    bool
	PaidAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UserName  string
	UserEmail string
}

func (q *Queries) ListExpenseSplitsByExpenseIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListExpenseSplitsByExpenseIDsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByExpenseIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsByExpenseIDsRow
	for rows.Next() {
		var i ListExpenseSplitsByExpenseIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.Amount,
			&i.IsPaid,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseSplitsByUser = `-- name: ListExpenseSplitsByUser :many
SELECT es.id, es.expense_id, es.user_id, es.amount, es.is_paid, es.paid_at, es.created_at, e.description AS expense_description
FROM expense_splits es
JOIN expenses e ON e.id = es.expense_id
WHERE es.user_id = $1 AND e.group_id = $2
ORDER BY e.competence_date DESC
`

type ListExpenseSplitsByUserParams struct {
	UserID  pgtype.UUID
	GroupID pgtype.UUID
}

type ListExpenseSplitsByUserRow struct {
	ID                 pgtype.UUID
	ExpenseID          pgtype.UUID
	UserID             pgtype.UUID
	Amount             pgtype.Numeric
	IsPaid             bool
	PaidAt             pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	ExpenseDescription string
}

func (q *Queries) ListExpenseSplitsByUser(ctx context.Context, arg ListExpenseSplitsByUserParams) ([]ListExpenseSplitsByUserRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByUser, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsByUserRow
	for rows.Next() {
		var i ListExpenseSplitsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.Amount,
			&i.IsPaid,
			&i.PaidAt,
			&i.CreatedAt,
			&i.ExpenseDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpenseSplitAsPaid = `-- name: MarkExpenseSplitAsPaid :exec
UPDATE expense_splits
SET is_paid = true,
    paid_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkExpenseSplitAsPaid(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markExpenseSplitAsPaid, id)
	return err
}
