// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (group_id, name)
VALUES ($1, $2)
RETURNING id, group_id, name, created_at
`

type CreateExpenseCategoryParams struct {
	GroupID pgtype.UUID
	Name    string
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.GroupID, arg.Name)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories
WHERE id = $1 AND group_id = $2
`

type DeleteExpenseCategoryParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
}

func (q *Queries) DeleteExpenseCategory(ctx context.Context, arg DeleteExpenseCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseCategory, arg.ID, arg.GroupID)
	return err
}

const getExpenseCategoryByID = `-- name: GetExpenseCategoryByID :one
SELECT id, group_id, name, created_at FROM expense_categories
WHERE id = $1
`

func (q *Queries) GetExpenseCategoryByID(ctx context.Context, id pgtype.UUID) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryByID, id)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenseCategoriesByGroup = `-- name: ListExpenseCategoriesByGroup :many
SELECT id, group_id, name, created_at FROM expense_categories
WHERE group_id = $1
ORDER BY name
`

func (q *Queries) ListExpenseCategoriesByGroup(ctx context.Context, groupID pgtype.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategoriesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET name = $3
WHERE id = $1 AND group_id = $2
RETURNING id, group_id, name, created_at
`

type UpdateExpenseCategoryParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
	Name    string
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory, arg.ID, arg.GroupID, arg.Name)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
