// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpensesByGroup = `-- name: CountExpensesByGroup :one
SELECT COUNT(*) FROM expenses
WHERE group_id = $1
  AND ($2::DATE IS NULL OR competence_date >= $2)
  AND ($3::DATE IS NULL OR competence_date <= $3)
  AND (installments = 1 OR parent_expense_id IS NOT NULL)
`

type CountExpensesByGroupParams struct {
	GroupID            pgtype.UUID
	CompetenceDateFrom pgtype.Date
	CompetenceDateTo   pgtype.Date
}

func (q *Queries) CountExpensesByGroup(ctx context.Context, arg CountExpensesByGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpensesByGroup, arg.GroupID, arg.CompetenceDateFrom, arg.CompetenceDateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (group_id, description, amount, category_id, competence_date, due_date, paid_by, split_mode, installments, first_due_date, is_fixed, parent_expense_id, installment_index, installment_total, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, group_id, description, amount, category_id, competence_date, due_date, paid_by, split_mode, installments, first_due_date, is_fixed, parent_expense_id, installment_index, installment_total, created_by, created_at, updated_at
`

type CreateExpenseParams struct {
	GroupID          pgtype.UUID
	Description      string
	Amount           pgtype.Numeric
	CategoryID       pgtype.UUID
	CompetenceDate   pgtype.Date
	DueDate          pgtype.Date
	PaidBy           pgtype.UUID
	SplitMode        string
	Installments     int32
	FirstDueDate     pgtype.Date
	IsFixed          bool
	ParentExpenseID  pgtype.UUID
	InstallmentIndex pgtype.Int4
	InstallmentTotal pgtype.Int4
	CreatedBy        pgtype.UUID
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.GroupID,
		arg.Description,
		arg.Amount,
		arg.CategoryID,
		arg.CompetenceDate,
		arg.DueDate,
		arg.PaidBy,
		arg.SplitMode,
		arg.Installments,
		arg.FirstDueDate,
		arg.IsFixed,
		arg.ParentExpenseID,
		arg.InstallmentIndex,
		arg.InstallmentTotal,
		arg.CreatedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Description,
		&i.Amount,
		&i.CategoryID,
		&i.CompetenceDate,
		&i.DueDate,
		&i.PaidBy,
		&i.SplitMode,
		&i.Installments,
		&i.FirstDueDate,
		&i.IsFixed,
		&i.ParentExpenseID,
		&i.InstallmentIndex,
		&i.InstallmentTotal,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const deleteExpensesByParent = `-- name: DeleteExpensesByParent :exec
DELETE FROM expenses
WHERE parent_expense_id = $1
`

func (q *Queries) DeleteExpensesByParent(ctx context.Context, parentExpenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpensesByParent, parentExpenseID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, group_id, description, amount, category_id, competence_date, due_date, paid_by, split_mode, installments, first_due_date, is_fixed, parent_expense_id, installment_index, installment_total, created_by, created_at, updated_at FROM expenses
WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id pgtype.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Description,
		&i.Amount,
		&i.CategoryID,
		&i.CompetenceDate,
		&i.DueDate,
		&i.PaidBy,
		&i.SplitMode,
		&i.Installments,
		&i.FirstDueDate,
		&i.IsFixed,
		&i.ParentExpenseID,
		&i.InstallmentIndex,
		&i.InstallmentTotal,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpensesByGroupFull = `-- name: ListExpensesByGroupFull :many
SELECT e.id, e.group_id, e.description, e.amount, e.category_id, e.competence_date, e.due_date, e.paid_by, e.split_mode, e.installments, e.first_due_date, e.is_fixed, e.parent_expense_id, e.installment_index, e.installment_total, e.created_by, e.created_at, e.updated_at, COUNT(*) OVER() AS total_count
FROM expenses e
WHERE e.group_id = $1
  AND ($2::DATE IS NULL OR e.competence_date >= $2)
  AND ($3::DATE IS NULL OR e.competence_date <= $3)
  AND ($4::TEXT IS NULL OR $4 = '' OR e.description ILIKE '%' || $4 || '%')
  AND ($5::UUID IS NULL OR EXISTS (
    SELECT 1 FROM expense_splits es WHERE es.expense_id = e.id AND es.user_id = $5
  ))
  AND (e.installments = 1 OR e.parent_expense_id IS NOT NULL)
ORDER BY e.competence_date DESC, e.created_at DESC
LIMIT $6 OFFSET $7
`

type ListExpensesByGroupFullParams struct {
	GroupID pgtype.UUID
	Column2 pgtype.Date
	Column3 pgtype.Date
	Column4 string
	Column5 pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListExpensesByGroupFullRow struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	Description      string
	Amount           pgtype.Numeric
	CategoryID       pgtype.UUID
	CompetenceDate   pgtype.Date
	DueDate          pgtype.Date
	PaidBy           pgtype.UUID
	SplitMode        string
	Installments     int32
	FirstDueDate     pgtype.Date
	IsFixed          bool
	ParentExpenseID  pgtype.UUID
	InstallmentIndex pgtype.Int4
	InstallmentTotal pgtype.Int4
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	TotalCount       int64
}

func (q *Queries) ListExpensesByGroupFull(ctx context.Context, arg ListExpensesByGroupFullParams) ([]ListExpensesByGroupFullRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroupFull,
		arg.GroupID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesByGroupFullRow
	for rows.Next() {
		var i ListExpensesByGroupFullRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CompetenceDate,
			&i.DueDate,
			&i.PaidBy,
			&i.SplitMode,
			&i.Installments,
			&i.FirstDueDate,
			&i.IsFixed,
			&i.ParentExpenseID,
			&i.InstallmentIndex,
			&i.InstallmentTotal,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalExpensesByGroup = `-- name: GetTotalExpensesByGroup :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) FROM expenses
WHERE group_id = $1
  AND (installments = 1 OR parent_expense_id IS NOT NULL)
`

func (q *Queries) GetTotalExpensesByGroup(ctx context.Context, groupID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalExpensesByGroup, groupID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const listExpensesByCategory = `-- name: ListExpensesByCategory :many
SELECT id, group_id, description, amount, category_id, competence_date, due_date, paid_by, split_mode, installments, first_due_date, is_fixed, parent_expense_id, installment_index, installment_total, created_by, created_at, updated_at FROM expenses
WHERE category_id = $1
ORDER BY competence_date DESC
`

func (q *Queries) ListExpensesByCategory(ctx context.Context, categoryID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CompetenceDate,
			&i.DueDate,
			&i.PaidBy,
			&i.SplitMode,
			&i.Installments,
			&i.FirstDueDate,
			&i.IsFixed,
			&i.ParentExpenseID,
			&i.InstallmentIndex,
			&i.InstallmentTotal,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByGroup = `-- name: ListExpensesByGroup :many
SELECT id, group_id, description, amount, category_id, competence_date, due_date, paid_by, split_mode, installments, first_due_date, is_fixed, parent_expense_id, installment_index, installment_total, created_by, created_at, updated_at FROM expenses
WHERE group_id = $1
  AND ($2::DATE IS NULL OR competence_date >= $2)
  AND ($3::DATE IS NULL OR competence_date <= $3)
  AND (installments = 1 OR parent_expense_id IS NOT NULL)
ORDER BY competence_date DESC, created_at DESC
LIMIT $4 OFFSET $5
`

type ListExpensesByGroupParams struct {
	GroupID            pgtype.UUID
	CompetenceDateFrom pgtype.Date
	CompetenceDateTo   pgtype.Date
	Limit              int32
	Offset             int32
}

func (q *Queries) ListExpensesByGroup(ctx context.Context, arg ListExpensesByGroupParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroup, arg.GroupID, arg.CompetenceDateFrom, arg.CompetenceDateTo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CompetenceDate,
			&i.DueDate,
			&i.PaidBy,
			&i.SplitMode,
			&i.Installments,
			&i.FirstDueDate,
			&i.IsFixed,
			&i.ParentExpenseID,
			&i.InstallmentIndex,
			&i.InstallmentTotal,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByParent = `-- name: ListExpensesByParent :many
SELECT id, group_id, description, amount, category_id, competence_date, due_date, paid_by, split_mode, installments, first_due_date, is_fixed, parent_expense_id, installment_index, installment_total, created_by, created_at, updated_at FROM expenses
WHERE parent_expense_id = $1
ORDER BY installment_index
`

func (q *Queries) ListExpensesByParent(ctx context.Context, parentExpenseID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByParent, parentExpenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CompetenceDate,
			&i.DueDate,
			&i.PaidBy,
			&i.SplitMode,
			&i.Installments,
			&i.FirstDueDate,
			&i.IsFixed,
			&i.ParentExpenseID,
			&i.InstallmentIndex,
			&i.InstallmentTotal,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUser = `-- name: ListExpensesByUser :many
SELECT e.id, e.group_id, e.description, e.amount, e.category_id, e.competence_date, e.due_date, e.paid_by, e.split_mode, e.installments, e.first_due_date, e.is_fixed, e.parent_expense_id, e.installment_index, e.installment_total, e.created_by, e.created_at, e.updated_at FROM expenses e
JOIN expense_splits es ON es.expense_id = e.id
WHERE es.user_id = $1
ORDER BY e.competence_date DESC, e.created_at DESC
`

func (q *Queries) ListExpensesByUser(ctx context.Context, userID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CompetenceDate,
			&i.DueDate,
			&i.PaidBy,
			&i.SplitMode,
			&i.Installments,
			&i.FirstDueDate,
			&i.IsFixed,
			&i.ParentExpenseID,
			&i.InstallmentIndex,
			&i.InstallmentTotal,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET description = COALESCE($2, description),
    amount = COALESCE($3, amount),
    competence_date = COALESCE($4, competence_date),
    due_date = COALESCE($5, due_date),
    category_id = COALESCE($6, category_id),
    split_mode = COALESCE($7, split_mode),
    updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, description, amount, category_id, competence_date, due_date, paid_by, split_mode, installments, first_due_date, is_fixed, parent_expense_id, installment_index, installment_total, created_by, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID             pgtype.UUID
	Description    string
	Amount         pgtype.Numeric
	CompetenceDate pgtype.Date
	DueDate        pgtype.Date
	CategoryID     pgtype.UUID
	SplitMode      string
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.CompetenceDate,
		arg.DueDate,
		arg.CategoryID,
		arg.SplitMode,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Description,
		&i.Amount,
		&i.CategoryID,
		&i.CompetenceDate,
		&i.DueDate,
		&i.PaidBy,
		&i.SplitMode,
		&i.Installments,
		&i.FirstDueDate,
		&i.IsFixed,
		&i.ParentExpenseID,
		&i.InstallmentIndex,
		&i.InstallmentTotal,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
