// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (group_id, created_by, description, total_amount, expense_date, due_date, category_id, split_type, is_installment, installment_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, group_id, created_by, description, total_amount, expense_date, due_date, category_id, split_type, is_installment, installment_count, created_at, updated_at
`

type CreateExpenseParams struct {
	GroupID          pgtype.UUID
	CreatedBy        pgtype.UUID
	Description      string
	TotalAmount      pgtype.Numeric
	ExpenseDate      pgtype.Date
	DueDate          pgtype.Date
	CategoryID       pgtype.UUID
	SplitType        string
	IsInstallment    bool
	InstallmentCount pgtype.Int2
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.GroupID,
		arg.CreatedBy,
		arg.Description,
		arg.TotalAmount,
		arg.ExpenseDate,
		arg.DueDate,
		arg.CategoryID,
		arg.SplitType,
		arg.IsInstallment,
		arg.InstallmentCount,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Description,
		&i.TotalAmount,
		&i.ExpenseDate,
		&i.DueDate,
		&i.CategoryID,
		&i.SplitType,
		&i.IsInstallment,
		&i.InstallmentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, group_id, created_by, description, total_amount, expense_date, due_date, category_id, split_type, is_installment, installment_count, created_at, updated_at FROM expenses
WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id pgtype.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Description,
		&i.TotalAmount,
		&i.ExpenseDate,
		&i.DueDate,
		&i.CategoryID,
		&i.SplitType,
		&i.IsInstallment,
		&i.InstallmentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalExpensesByGroup = `-- name: GetTotalExpensesByGroup :one
SELECT COALESCE(SUM(total_amount), 0)::NUMERIC(12,2) FROM expenses
WHERE group_id = $1
`

func (q *Queries) GetTotalExpensesByGroup(ctx context.Context, groupID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalExpensesByGroup, groupID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const listExpensesByCategory = `-- name: ListExpensesByCategory :many
SELECT id, group_id, created_by, description, total_amount, expense_date, due_date, category_id, split_type, is_installment, installment_count, created_at, updated_at FROM expenses
WHERE category_id = $1
ORDER BY expense_date DESC
`

func (q *Queries) ListExpensesByCategory(ctx context.Context, categoryID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Description,
			&i.TotalAmount,
			&i.ExpenseDate,
			&i.DueDate,
			&i.CategoryID,
			&i.SplitType,
			&i.IsInstallment,
			&i.InstallmentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByGroup = `-- name: ListExpensesByGroup :many
SELECT id, group_id, created_by, description, total_amount, expense_date, due_date, category_id, split_type, is_installment, installment_count, created_at, updated_at FROM expenses
WHERE group_id = $1
ORDER BY expense_date DESC, created_at DESC
`

func (q *Queries) ListExpensesByGroup(ctx context.Context, groupID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Description,
			&i.TotalAmount,
			&i.ExpenseDate,
			&i.DueDate,
			&i.CategoryID,
			&i.SplitType,
			&i.IsInstallment,
			&i.InstallmentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUser = `-- name: ListExpensesByUser :many
SELECT e.id, e.group_id, e.created_by, e.description, e.total_amount, e.expense_date, e.due_date, e.category_id, e.split_type, e.is_installment, e.installment_count, e.created_at, e.updated_at FROM expenses e
JOIN expense_splits es ON es.expense_id = e.id
WHERE es.user_id = $1
ORDER BY e.expense_date DESC, e.created_at DESC
`

func (q *Queries) ListExpensesByUser(ctx context.Context, userID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Description,
			&i.TotalAmount,
			&i.ExpenseDate,
			&i.DueDate,
			&i.CategoryID,
			&i.SplitType,
			&i.IsInstallment,
			&i.InstallmentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET description = COALESCE($2, description),
    total_amount = COALESCE($3, total_amount),
    expense_date = COALESCE($4, expense_date),
    due_date = $5,
    category_id = $6,
    split_type = COALESCE($7, split_type),
    updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, created_by, description, total_amount, expense_date, due_date, category_id, split_type, is_installment, installment_count, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID          pgtype.UUID
	Description string
	TotalAmount pgtype.Numeric
	ExpenseDate pgtype.Date
	DueDate     pgtype.Date
	CategoryID  pgtype.UUID
	SplitType   string
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Description,
		arg.TotalAmount,
		arg.ExpenseDate,
		arg.DueDate,
		arg.CategoryID,
		arg.SplitType,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Description,
		&i.TotalAmount,
		&i.ExpenseDate,
		&i.DueDate,
		&i.CategoryID,
		&i.SplitType,
		&i.IsInstallment,
		&i.InstallmentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
