// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (slug, label)
VALUES ($1, $2)
RETURNING id, slug, label, created_at
`

type CreateExpenseCategoryParams struct {
	Slug  string
	Label string
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.Slug, arg.Label)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories
WHERE id = $1
`

func (q *Queries) DeleteExpenseCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseCategory, id)
	return err
}

const getExpenseCategoryByID = `-- name: GetExpenseCategoryByID :one
SELECT id, slug, label, created_at FROM expense_categories
WHERE id = $1
`

func (q *Queries) GetExpenseCategoryByID(ctx context.Context, id pgtype.UUID) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryByID, id)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, slug, label, created_at FROM expense_categories
ORDER BY label
`

func (q *Queries) ListExpenseCategories(ctx context.Context) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET slug = $2,
    label = $3
WHERE id = $1
RETURNING id, slug, label, created_at
`

type UpdateExpenseCategoryParams struct {
	ID    pgtype.UUID
	Slug  string
	Label string
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory, arg.ID, arg.Slug, arg.Label)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}
