// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveGroupMembers = `-- name: CountActiveGroupMembers :one
SELECT COUNT(*) FROM group_members
WHERE group_id = $1 AND is_active = true
`

func (q *Queries) CountActiveGroupMembers(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, group_id, user_id, role, joined_at, left_at, is_active
`

type CreateGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
	Role    string
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.IsActive,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, group_id, user_id, role, joined_at, left_at, is_active FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.IsActive,
	)
	return i, err
}

const getGroupMemberByID = `-- name: GetGroupMemberByID :one
SELECT id, group_id, user_id, role, joined_at, left_at, is_active FROM group_members
WHERE id = $1
`

func (q *Queries) GetGroupMemberByID(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByID, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.IsActive,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.id, gm.group_id, gm.user_id, gm.role, gm.joined_at, gm.left_at, gm.is_active, u.name, u.email, u.avatar_url
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1 AND gm.is_active = true
ORDER BY gm.joined_at
`

type ListGroupMembersRow struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	JoinedAt  pgtype.Timestamptz
	LeftAt    pgtype.Timestamptz
	IsActive  bool
	Name      string
	Email     string
	AvatarUrl pgtype.Text
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
			&i.IsActive,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
UPDATE group_members
SET is_active = false,
    left_at = NOW()
WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :one
UPDATE group_members
SET role = $3
WHERE group_id = $1 AND user_id = $2
RETURNING id, group_id, user_id, role, joined_at, left_at, is_active
`

type UpdateGroupMemberRoleParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
	Role    string
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberRole, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
		&i.IsActive,
	)
	return i, err
}
