// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, invite_token)
VALUES ($1, gen_random_uuid()::text)
RETURNING id, name, description, monthly_fee, photo_url, invite_token, created_at, updated_at
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MonthlyFee,
		&i.PhotoUrl,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, monthly_fee, photo_url, invite_token, created_at, updated_at FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MonthlyFee,
		&i.PhotoUrl,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupsByUserID = `-- name: ListGroupsByUserID :many
SELECT g.id, g.name, g.description, g.monthly_fee, g.photo_url, g.invite_token, g.created_at, g.updated_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY g.name
`

func (q *Queries) ListGroupsByUserID(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MonthlyFee,
			&i.PhotoUrl,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateInviteToken = `-- name: RegenerateInviteToken :one
UPDATE groups
SET invite_token = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, monthly_fee, photo_url, invite_token, created_at, updated_at
`

type RegenerateInviteTokenParams struct {
	ID          pgtype.UUID
	InviteToken pgtype.Text
}

func (q *Queries) RegenerateInviteToken(ctx context.Context, arg RegenerateInviteTokenParams) (Group, error) {
	row := q.db.QueryRow(ctx, regenerateInviteToken, arg.ID, arg.InviteToken)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MonthlyFee,
		&i.PhotoUrl,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    monthly_fee = COALESCE($4, monthly_fee),
    photo_url = COALESCE($5, photo_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, monthly_fee, photo_url, invite_token, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	MonthlyFee  pgtype.Numeric
	PhotoUrl    pgtype.Text
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MonthlyFee,
		arg.PhotoUrl,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MonthlyFee,
		&i.PhotoUrl,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
