// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID
	GroupID    pgtype.UUID
	UserID     pgtype.UUID
	EntityType string
	EntityID   pgtype.UUID
	Action     string
	Changes    []byte
	CreatedAt  pgtype.Timestamptz
}

type Expense struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	Description      string
	Amount           pgtype.Numeric
	CategoryID       pgtype.UUID
	CompetenceDate   pgtype.Date
	DueDate          pgtype.Date
	PaidBy           pgtype.UUID
	SplitMode        string
	Installments     int32
	FirstDueDate     pgtype.Date
	IsFixed          bool
	ParentExpenseID  pgtype.UUID
	InstallmentIndex pgtype.Int4
	InstallmentTotal pgtype.Int4
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ExpenseCategory struct {
	ID        pgtype.UUID
	Slug      string
	Label     string
	CreatedAt pgtype.Timestamptz
}

type ExpenseSplit struct {
	ID        pgtype.UUID
	ExpenseID pgtype.UUID
	UserID    pgtype.UUID
	Amount    pgtype.Numeric
	IsPaid    bool
	PaidAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Group struct {
	ID          pgtype.UUID
	Name        string
	Description string
	MonthlyFee  pgtype.Numeric
	PhotoUrl    pgtype.Text
	InviteToken pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GroupMember struct {
	ID       pgtype.UUID
	GroupID  pgtype.UUID
	UserID   pgtype.UUID
	IsAdmin  bool
	JoinedAt pgtype.Timestamptz
}

type Notification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Title     string
	Message   string
	IsRead    bool
	RelatedID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Payment struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	PayerID     pgtype.UUID
	ReceiverID  pgtype.UUID
	Amount      pgtype.Numeric
	PaymentDate pgtype.Date
	Status      string
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ConfirmedAt pgtype.Timestamptz
	CancelledAt pgtype.Timestamptz
}

type PaymentAttachment struct {
	ID         pgtype.UUID
	PaymentID  pgtype.UUID
	FilePath   string
	FileType   string
	FileSize   int32
	UploadedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Task struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	Title       string
	Description string
	AssignedTo  pgtype.UUID
	CreatedBy   pgtype.UUID
	Status      string
	Position    int32
	DueDate     pgtype.Date
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TaskOccurrence struct {
	ID          pgtype.UUID
	TaskID      pgtype.UUID
	DueDate     pgtype.Date
	Status      string
	CompletedBy pgtype.UUID
	CompletedAt pgtype.Timestamptz
	DiscardedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Phone        pgtype.Text
	Document     pgtype.Text
	BirthDate    pgtype.Date
	Cep          pgtype.Text
	IsAdmin      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
