// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_attachment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentAttachment = `-- name: CreatePaymentAttachment :one
INSERT INTO payment_attachments (payment_id, file_path, file_type, file_size)
VALUES ($1, $2, $3, $4)
RETURNING id, payment_id, file_path, file_type, file_size, uploaded_at
`

type CreatePaymentAttachmentParams struct {
	PaymentID pgtype.UUID
	FilePath  string
	FileType  string
	FileSize  int32
}

func (q *Queries) CreatePaymentAttachment(ctx context.Context, arg CreatePaymentAttachmentParams) (PaymentAttachment, error) {
	row := q.db.QueryRow(ctx, createPaymentAttachment,
		arg.PaymentID,
		arg.FilePath,
		arg.FileType,
		arg.FileSize,
	)
	var i PaymentAttachment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}

const deletePaymentAttachment = `-- name: DeletePaymentAttachment :exec
DELETE FROM payment_attachments
WHERE id = $1
`

func (q *Queries) DeletePaymentAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePaymentAttachment, id)
	return err
}

const getPaymentAttachmentByID = `-- name: GetPaymentAttachmentByID :one
SELECT id, payment_id, file_path, file_type, file_size, uploaded_at FROM payment_attachments
WHERE id = $1
`

func (q *Queries) GetPaymentAttachmentByID(ctx context.Context, id pgtype.UUID) (PaymentAttachment, error) {
	row := q.db.QueryRow(ctx, getPaymentAttachmentByID, id)
	var i PaymentAttachment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}

const listPaymentAttachmentsByPayment = `-- name: ListPaymentAttachmentsByPayment :many
SELECT id, payment_id, file_path, file_type, file_size, uploaded_at FROM payment_attachments
WHERE payment_id = $1
ORDER BY uploaded_at
`

func (q *Queries) ListPaymentAttachmentsByPayment(ctx context.Context, paymentID pgtype.UUID) ([]PaymentAttachment, error) {
	rows, err := q.db.Query(ctx, listPaymentAttachmentsByPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAttachment
	for rows.Next() {
		var i PaymentAttachment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.FilePath,
			&i.FileType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
