// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPayment = `-- name: CancelPayment :exec
UPDATE payments
SET status = 'cancelled',
    cancelled_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CancelPayment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelPayment, id)
	return err
}

const confirmPayment = `-- name: ConfirmPayment :exec
UPDATE payments
SET status = 'confirmed',
    confirmed_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ConfirmPayment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmPayment, id)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (group_id, payer_id, receiver_id, amount, payment_date, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, payer_id, receiver_id, amount, payment_date, status, notes, created_at, confirmed_at, cancelled_at
`

type CreatePaymentParams struct {
	GroupID     pgtype.UUID
	PayerID     pgtype.UUID
	ReceiverID  pgtype.UUID
	Amount      pgtype.Numeric
	PaymentDate pgtype.Date
	Notes       pgtype.Text
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.GroupID,
		arg.PayerID,
		arg.ReceiverID,
		arg.Amount,
		arg.PaymentDate,
		arg.Notes,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PayerID,
		&i.ReceiverID,
		&i.Amount,
		&i.PaymentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments
WHERE id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePayment, id)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, group_id, payer_id, receiver_id, amount, payment_date, status, notes, created_at, confirmed_at, cancelled_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PayerID,
		&i.ReceiverID,
		&i.Amount,
		&i.PaymentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listPaymentsByGroup = `-- name: ListPaymentsByGroup :many
SELECT p.id, p.group_id, p.payer_id, p.receiver_id, p.amount, p.payment_date, p.status, p.notes, p.created_at, p.confirmed_at, p.cancelled_at, pu.name AS payer_name, ru.name AS receiver_name
FROM payments p
JOIN users pu ON pu.id = p.payer_id
JOIN users ru ON ru.id = p.receiver_id
WHERE p.group_id = $1
ORDER BY p.payment_date DESC, p.created_at DESC
`

type ListPaymentsByGroupRow struct {
	ID           pgtype.UUID
	GroupID      pgtype.UUID
	PayerID      pgtype.UUID
	ReceiverID   pgtype.UUID
	Amount       pgtype.Numeric
	PaymentDate  pgtype.Date
	Status       string
	Notes        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	ConfirmedAt  pgtype.Timestamptz
	CancelledAt  pgtype.Timestamptz
	PayerName    string
	ReceiverName string
}

func (q *Queries) ListPaymentsByGroup(ctx context.Context, groupID pgtype.UUID) ([]ListPaymentsByGroupRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsByGroupRow
	for rows.Next() {
		var i ListPaymentsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PayerID,
			&i.ReceiverID,
			&i.Amount,
			&i.PaymentDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CancelledAt,
			&i.PayerName,
			&i.ReceiverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT p.id, p.group_id, p.payer_id, p.receiver_id, p.amount, p.payment_date, p.status, p.notes, p.created_at, p.confirmed_at, p.cancelled_at, g.name AS group_name
FROM payments p
JOIN groups g ON g.id = p.group_id
WHERE p.payer_id = $1 OR p.receiver_id = $1
ORDER BY p.payment_date DESC, p.created_at DESC
`

type ListPaymentsByUserRow struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	PayerID     pgtype.UUID
	ReceiverID  pgtype.UUID
	Amount      pgtype.Numeric
	PaymentDate pgtype.Date
	Status      string
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ConfirmedAt pgtype.Timestamptz
	CancelledAt pgtype.Timestamptz
	GroupName   string
}

func (q *Queries) ListPaymentsByUser(ctx context.Context, payerID pgtype.UUID) ([]ListPaymentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, payerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsByUserRow
	for rows.Next() {
		var i ListPaymentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PayerID,
			&i.ReceiverID,
			&i.Amount,
			&i.PaymentDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CancelledAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPaymentsByUser = `-- name: ListPendingPaymentsByUser :many
SELECT id, group_id, payer_id, receiver_id, amount, payment_date, status, notes, created_at, confirmed_at, cancelled_at FROM payments
WHERE (payer_id = $1 OR receiver_id = $1)
  AND status = 'pending'
ORDER BY payment_date
`

func (q *Queries) ListPendingPaymentsByUser(ctx context.Context, payerID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPendingPaymentsByUser, payerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.PayerID,
			&i.ReceiverID,
			&i.Amount,
			&i.PaymentDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
