// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: split_tag.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSplitTagMember = `-- name: AddSplitTagMember :one
INSERT INTO split_tag_members (split_tag_id, user_id)
VALUES ($1, $2)
RETURNING id, split_tag_id, user_id
`

type AddSplitTagMemberParams struct {
	SplitTagID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) AddSplitTagMember(ctx context.Context, arg AddSplitTagMemberParams) (SplitTagMember, error) {
	row := q.db.QueryRow(ctx, addSplitTagMember, arg.SplitTagID, arg.UserID)
	var i SplitTagMember
	err := row.Scan(&i.ID, &i.SplitTagID, &i.UserID)
	return i, err
}

const createSplitTag = `-- name: CreateSplitTag :one
INSERT INTO split_tags (group_id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, group_id, name, created_by, created_at
`

type CreateSplitTagParams struct {
	GroupID   pgtype.UUID
	Name      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateSplitTag(ctx context.Context, arg CreateSplitTagParams) (SplitTag, error) {
	row := q.db.QueryRow(ctx, createSplitTag, arg.GroupID, arg.Name, arg.CreatedBy)
	var i SplitTag
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSplitTag = `-- name: DeleteSplitTag :exec
DELETE FROM split_tags
WHERE id = $1 AND group_id = $2
`

type DeleteSplitTagParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
}

func (q *Queries) DeleteSplitTag(ctx context.Context, arg DeleteSplitTagParams) error {
	_, err := q.db.Exec(ctx, deleteSplitTag, arg.ID, arg.GroupID)
	return err
}

const getSplitTagByID = `-- name: GetSplitTagByID :one
SELECT id, group_id, name, created_by, created_at FROM split_tags
WHERE id = $1
`

func (q *Queries) GetSplitTagByID(ctx context.Context, id pgtype.UUID) (SplitTag, error) {
	row := q.db.QueryRow(ctx, getSplitTagByID, id)
	var i SplitTag
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSplitTagMembers = `-- name: ListSplitTagMembers :many
SELECT stm.id, stm.split_tag_id, stm.user_id, u.name AS user_name
FROM split_tag_members stm
JOIN users u ON u.id = stm.user_id
WHERE stm.split_tag_id = $1
`

type ListSplitTagMembersRow struct {
	ID         pgtype.UUID
	SplitTagID pgtype.UUID
	UserID     pgtype.UUID
	UserName   string
}

func (q *Queries) ListSplitTagMembers(ctx context.Context, splitTagID pgtype.UUID) ([]ListSplitTagMembersRow, error) {
	rows, err := q.db.Query(ctx, listSplitTagMembers, splitTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSplitTagMembersRow
	for rows.Next() {
		var i ListSplitTagMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.SplitTagID,
			&i.UserID,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitTagsByGroup = `-- name: ListSplitTagsByGroup :many
SELECT id, group_id, name, created_by, created_at FROM split_tags
WHERE group_id = $1
ORDER BY name
`

func (q *Queries) ListSplitTagsByGroup(ctx context.Context, groupID pgtype.UUID) ([]SplitTag, error) {
	rows, err := q.db.Query(ctx, listSplitTagsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SplitTag
	for rows.Next() {
		var i SplitTag
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSplitTagMember = `-- name: RemoveSplitTagMember :exec
DELETE FROM split_tag_members
WHERE split_tag_id = $1 AND user_id = $2
`

type RemoveSplitTagMemberParams struct {
	SplitTagID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) RemoveSplitTagMember(ctx context.Context, arg RemoveSplitTagMemberParams) error {
	_, err := q.db.Exec(ctx, removeSplitTagMember, arg.SplitTagID, arg.UserID)
	return err
}
